# Generated by Django 2.1.5 on 2019-02-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='头像'),
        ),
    ]
