# Generated by Django 2.1.5 on 2019-02-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190210_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bolg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.BlogInfo', verbose_name='所属博客'),
        ),
    ]
