# Generated by Django 2.1.5 on 2019-02-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_article_bolg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='bolg',
            new_name='blog',
        ),
    ]
