# Generated by Django 2.1.5 on 2019-02-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20190214_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_updown',
            name='up',
            field=models.BooleanField(default=True, null=True, verbose_name='是否赞'),
        ),
    ]
