# Generated by Django 2.1.5 on 2019-04-27 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20190214_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='repository.Article_Tag', to='repository.Tag'),
        ),
        migrations.AddField(
            model_name='article_comment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Article', verbose_name='评论文章'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article_updown',
            name='up',
            field=models.BooleanField(default=True, verbose_name='是否赞'),
        ),
        migrations.AlterUniqueTogether(
            name='article_tag',
            unique_together={('article_id', 'tag_id')},
        ),
    ]
