# Generated by Django 2.1.5 on 2019-05-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20190427_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
        migrations.AddField(
            model_name='article',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='踩数量'),
        ),
        migrations.AddField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读数量'),
        ),
        migrations.AddField(
            model_name='article',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
    ]
