# Generated by Django 2.1.5 on 2019-05-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20190501_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
