# Generated by Django 2.1.5 on 2019-05-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_userinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='article_comment',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='article_detail',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='article_tag',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='article_updown',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='userfans',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='reportobstacles',
            name='status',
            field=models.IntegerField(choices=[(0, '已删除'), (1, '待处理'), (2, '处理中'), (3, '已处理')], default=None),
        ),
    ]
