# Generated by Django 2.1.5 on 2019-05-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20190525_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportobstacles',
            name='evaluate',
            field=models.IntegerField(choices=[(1, '不满意'), (2, '一般'), (3, '很好')], default=2, null=True),
        ),
        migrations.AddField(
            model_name='reportobstacles',
            name='processSolution',
            field=models.TextField(null=True, verbose_name='处理方法'),
        ),
        migrations.AlterField(
            model_name='reportobstacles',
            name='status',
            field=models.IntegerField(choices=[(0, '已删除'), (1, '待处理'), (2, '处理中'), (3, '已处理')], default=1),
        ),
    ]
