# Generated by Django 2.1.5 on 2019-05-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20190526_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportObstacles',
            new_name='Trouble',
        ),
    ]
